# Site
repository: benitezluciano/benitezluciano.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Gabriel Luciano Benítez 
title: Técnico Superior en Logística
email: lucianogrbenitez@gmail.com
phone: +54 9 3772 409382
# web: https://calendly.com/benitezluciano

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: benitezluciano
# github_username:  benitezluciano
# stackoverflow_username: "10876680"
# dribbble_username: benitezluciano
# facebook_username: fernando.albertengo.9
# flickr_username: jekyll
# instagram_username: benitezluciano
linkedin_username: benitezluciano
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: UCR-B2xeA9tiugN0XsnmWKxA
# googleplus_username: +fernando.albertengo
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
 - title: Whatsapp
   icon: fa fa-whatsapp
   url: https://api.whatsapp.com/send?phone=5493772409382

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Acerca de mi
about_profile_image: images/profile.jpeg
about_content: | 
  Soy Gabriel Luciano Benítez, un joven de 24 años, <mark>Técnico en Logística</mark> y estudiante de <mark>Analista de Sistemas de Información</mark>. Originario de Alvear (Corrientes) y residente en Rosario, me apasiona la tecnología, y el aprendizaje continuo. 
  
  Como profesional, soy <mark>proactivo</mark>, <mark>responsable</mark> y <mark>adaptable</mark>, y me desenvuelvo perfectamente trabajando en equipo. 
  
  Mi experiencia en logística, combinada con los conocimientos que adquiero actualmente en mis estudios, me permite abordar los desafíos con una visión integral. 
  
  Busco activamente oportunidades que me permitan poner en práctica mis conocimientos y seguir desarrollándome en un entorno dinámico e innovador.

content:
  - title: Experiencia
    layout: list
    content:
      - layout: left
        title: Clamex S.A
        link: https://ar.linkedin.com/company/clamex-s-a
        sub_title: Venta de Telecomunicaciones Corporativas
        caption: Marzo 2024 - actualidad
        description: | 
          Mis funciones son, pero no se limitan a:
          - Captar y fidelizar clientes a través de llamadas telefónicas.
          - Brindar asesoramiento personalizado y resolver consultas de clientes.
          - Utilizar <mark>Salesforce</mark>, <mark>Stealth</mark> y <mark>Excel</mark> para gestionar carteras de clientes y optimizar el proceso de ventas.

          Referencias al: +54 9 341 6 861169 (Angélica)

      - layout: left
        title: Oroño Metal S.A
        link: https://ometal.com.ar/
        sub_title: Auxiliar de Almacén y Control de Stock
        caption: Junio 2022 - Febrero 2023
        description: | 
          Mis funciones principales incluyeron:
          - Atender y asistir a los clientes, tanto en persona como por teléfono.
          - Recepcionar y coordinar la llegada de los proveedores.
          - Llevar a cabo la gestión y control del stock, garantizando la disponibilidad de los productos y realizando un seguimiento de los niveles de inventario.

          Referencias al: info@ometal.com.ar 

      - layout: left
        title: Vía Bariloche S.A
        link: https://www.viabariloche.com.ar/
        sub_title: Boletería
        caption: Febrero 2020 - Abril 2022
        description: | 
          Mis funciones incluyeron pero no se limitaron a:
          - Atención al público
          - Venta de pasajes en efectivo y con tarjeta
          - Cierre de caja

          Referencias al tel.: 3772-510593 o por email franciscoalvear07@hotmail.com (Francisco Alcaraz)
      - layout: left
        title: Vía Cargo S.A
        link: https://www.viacargo.com.ar/
        sub_title: Encomiendas
        caption: Febrero 2020 - Abril 2022
        description: |
          Operaciones logisticas de recepción y envíos de encomiendas, incluyendo:
          - Recepcion vehiculos logisticos
          - Alta de datos a sistema de encomiendas entrantes
          - Etiquetado de encomiendas por enviar
          - Facturación
          - Entrega de encomiendas al publico
  - title: Inglés
    layout: list
    content:
      - layout: top-middle
        title: Curso Nivel Adulto 1
        sub_title: Speak up English Institute
  - title: Educación
    layout: list
    content:
      - layout: left
        title: Terciario Urquiza
        caption: 2024 - Actualidad
        sub_title: Analista Funcional de Sistemas Informaticos  
        description: | 
          Un estudiante de analista funcional aprende a diseñar y modelar sistemas informáticos que satisfacen las necesidades de un negocio, actuando como puente entre los usuarios y los equipos de desarrollo.
      
      - layout: left
        title: UTN.BA
        caption: 2023
        sub_title: Gestión De Transporte  
        description: | 
         Aprendi a reconocer la importancia del transporte en los costos de logística de las empresas, su complejidad y variantes, desarrollar habilidades en gestión del transporte y análisis de costos. 
      
      - layout: left
        title: Crehana Education
        caption: 2023
        sub_title: Curso de Excel Intermedio
        description: | 
          Aprendí a utilizar nuevas herramientas como filtros, tablas dinámicas, gráficos, macros y funciones avanzadas. Mejoré mi eficiencia y productividad en la gestión de información, trabajando con hojas de cálculo más complejas y mejorando la organización y presentación de datos. 
      - layout: left
        title: Instituto Superior de Formación docente de Alvear
        caption: 2019 - 2021
        sub_title: Técnico Superior en Logística 
        description: | 
          Fui capacitado para la gestión y ejecución de variados procesos, entre ellos: 
          - Operaciones de compras y abastecimientos
          - Inventariado y almacenamiento
          - Operaciones de distribución y gestion de transporte, desde el proveedor hasta el cliente final.
      - layout: left
        title: Colegio Secundaria Doctor Mamerto Acuña
        caption: 2011 - 2017
        sub_title: Bachiller en Economía y Administración
        description: | 
          Aprendí de las diferentes organizaciones e instituciones relacionadas con el ámbito social, económico, político y cultural. 
          
          Esto incluye a visualizar las principales problemáticas organizacionales, conforme a las variables internas y del entorno, asi como los distintos indicadores económicos y sus herramientas de medición.

  - title: Objetivos
    layout: text
    content: | 
      Además de querer seguir creciendo profesionalmente, participando en el ámbito laboral, deseo seguir capacitándome en otras habilidades como, por ejemplo, desarrollo de software y el idioma Inglés. 
      
      En mi tiempo libre disfruto de mi pasión por la musica y me relajo haciendo entrenamiento fisico. 
      
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
